# Generated by Django 6.0 on 2025-12-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_following_customuser_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
