# Generated by Django 6.0 on 2025-12-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_comment_updated_at_remove_post_updated_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
